apiVersion: v1
kind: RAGEngine
metadata:
  name: dify-rag
  label:
    en_US: Dify Knowledge Base
    zh_Hans: Dify 知识库
    ja_JP: Dify 知識ベース
  description:
    en_US: Retrieve knowledge from Dify knowledge bases
    zh_Hans: 从 Dify 知识库中检索知识
    ja_JP: Dify 知識ベースから知識を検索
spec:
  creation_schema:
    - name: api_base_url
      label:
        en_US: API Base URL
        zh_Hans: API 基础地址
      description:
        en_US: 'Base URL for Dify API (e.g., https://api.dify.ai/v1 for cloud, or your self-hosted URL)'
        zh_Hans: 'Dify API 基础地址（云端版本使用 https://api.dify.ai/v1，自托管版本使用您的服务器地址）'
        ja_JP: 'Dify API ベース URL（クラウド版は https://api.dify.ai/v1、セルフホストの場合はサーバーの URL）'
      type: string
      default: https://api.dify.ai/v1
      required: true
    - name: dify_apikey
      label:
        en_US: API Key
        zh_Hans: API 密钥
      description:
        en_US: 'API key from your Dify instance'
        zh_Hans: '从您的 Dify 实例获取的 API Key'
        ja_JP: 'Dify インスタンスから取得した API Key'
      type: password
      required: true
    - name: dataset_id
      label:
        en_US: Dataset ID
        zh_Hans: 数据集 ID
        ja_JP: データセット ID
      description:
        en_US: 'The UUID of the Dify Dataset to retrieve from'
        zh_Hans: '要检索的 Dify 数据集 UUID'
        ja_JP: 'Dify ナレッジベース/データセットの ID'
      type: string
      required: true
    - name: search_method
      label:
        en_US: Search Method
        zh_Hans: 检索模式
        ja_JP: 検索方法
      description:
        en_US: 'The search method to use, recommended to select the method that matches your dataset type'
        zh_Hans: '使用的搜索方法，推荐选择与您的数据集类型匹配的方法'
        ja_JP: '使用する検索方法，データセットのタイプに合わせて選択することをお勧めします'
      type: select
      default: keyword_search
      options:
        - name: keyword_search
          label:
            en_US: Keyword Search
            zh_Hans: 关键词检索
            ja_JP: キーワード検索
        - name: semantic_search
          label:
            en_US: Semantic Search
            zh_Hans: 语义检索
            ja_JP: セマンティック検索
        - name: hybrid_search
          label:
            en_US: Hybrid Search
            zh_Hans: 混合检索
            ja_JP: ハイブリッド検索
      required: false
    - name: score_threshold
      label:
        en_US: Score Threshold
        zh_Hans: 分数阈值
      description:
        en_US: 'Minimum relevance score (0-1)'
        zh_Hans: '最小相关性分数 (0-1)'
        ja_JP: '最小関連性スコア (0-1)'
      type: float
      default: 0.5
      required: false
  retrieval_schema: []
execution:
  python:
    path: engine.py
    attr: DifyRAGEngine
