# Auto generated by LangBot Plugin SDK.
# Please refer to https://docs.langbot.app/en/plugin/dev/tutor.html for more details.
from __future__ import annotations

import json
from typing import Any
import httpx
import logging
import traceback
from langbot_plugin.api.definition.components.knowledge_retriever.retriever import KnowledgeRetriever
from langbot_plugin.api.entities.builtin.provider.message import ContentElement
from langbot_plugin.api.entities.builtin.rag.context import RetrievalContext, RetrievalResultEntry


logger = logging.getLogger(__name__)


class FastGPT(KnowledgeRetriever):

    async def retrieve(self, context: RetrievalContext) -> list[RetrievalResultEntry]:
        """Retrieve knowledge from FastGPT knowledge base"""

        # Get configuration values
        api_base_url = self.config.get('api_base_url', 'http://localhost:3000')
        api_key = self.config.get('api_key')
        dataset_id = self.config.get('dataset_id')
        limit = self.config.get('limit', 5000)
        similarity = self.config.get('similarity', 0.0)
        search_mode = self.config.get('search_mode', 'embedding')
        using_rerank = self.config.get('using_rerank', False)
        dataset_search_using_extension_query = self.config.get('dataset_search_using_extension_query', False)
        dataset_search_extension_model = self.config.get('dataset_search_extension_model', '')
        dataset_search_extension_bg = self.config.get('dataset_search_extension_bg', '')

        if not api_key or not dataset_id:
            logger.error("Missing required configuration: api_key or dataset_id")
            return []

        # Remove trailing slash from base URL if present
        api_base_url = api_base_url.rstrip('/')

        # Prepare the API request
        url = f"{api_base_url}/api/core/dataset/searchTest"
        headers = {
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json"
        }

        payload = {
            "datasetId": dataset_id,
            "text": context.query,
            "limit": int(limit),
            "similarity": float(similarity),
            "searchMode": search_mode,
            "usingReRank": bool(using_rerank),
        }

        # Add optional extension query parameters if configured
        if dataset_search_using_extension_query:
            payload["datasetSearchUsingExtensionQuery"] = True
            if dataset_search_extension_model:
                payload["datasetSearchExtensionModel"] = dataset_search_extension_model
            if dataset_search_extension_bg:
                payload["datasetSearchExtensionBg"] = dataset_search_extension_bg

        try:
            # Make the API request
            async with httpx.AsyncClient() as client:
                response = await client.post(url, json=payload, headers=headers, timeout=30.0)
                response.raise_for_status()

                result = response.json()

                # Parse the response and convert to RetrievalResultEntry
                results = []
                data_list = result.get('data', [])

                for record in data_list:
                    # Combine q (main data) and a (auxiliary data) as content
                    content_parts = []
                    if record.get('q'):
                        content_parts.append(record['q'])
                    if record.get('a'):
                        content_parts.append(record['a'])

                    content_text = '\n'.join(content_parts) if content_parts else ''

                    entry = RetrievalResultEntry(
                        id=record.get('id', ''),
                        content=[ContentElement.from_text(content_text)],
                        metadata={
                            'dataset_id': record.get('datasetId', ''),
                            'collection_id': record.get('collectionId', ''),
                            'source_name': record.get('sourceName', ''),
                            'source_id': record.get('sourceId', ''),
                            'score': record.get('score', 0.0),
                        },
                        # Convert score to distance (higher score = lower distance)
                        distance=1.0 - float(record.get('score', 0.0)) if record.get('score') is not None else 0.5,
                    )
                    results.append(entry)

                logger.info(f"Retrieved {len(results)} chunks from FastGPT dataset {dataset_id}")
                return results

        except httpx.HTTPStatusError as e:
            logger.error(f"HTTP error from FastGPT API: {e.response.status_code} - {e.response.text}")
            return []
        except httpx.RequestError as e:
            logger.error(f"Request error when calling FastGPT API: {str(e)}")
            return []
        except Exception as e:
            traceback.print_exc()
            logger.error(f"Unexpected error during retrieval: {str(e)}")
            return []
