# Auto generated by LangBot Plugin SDK.
# Please refer to https://docs.langbot.app/en/plugin/dev/tutor.html for more details.
from __future__ import annotations

from langbot_plugin.api.definition.components.common.event_listener import EventListener
from langbot_plugin.api.entities import events, context
from langbot_plugin.api.entities.builtin.platform import message as platform_message
from langbot_plugin.api.entities.builtin.provider import message as provider_message


class DefaultEventListener(EventListener):

    def __init__(self):
        super().__init__()
        
        @self.handler(events.PersonNormalMessageReceived)
        async def handler(event_context: context.EventContext):
            print("Hello LangBot Plugin!")
            print(event_context)

            event_context.prevent_default()

            event_context.event.reply_message_chain = platform_message.MessageChain([
                platform_message.Plain(text=f"Hello from LangBot Plugin!"),
            ])
            
            # await event_context.reply(
            #     platform_message.MessageChain([
            #         platform_message.Plain(text=f"Hello from LangBot Plugin!"),
            #     ])
            # )
