# Auto generated by LangBot Plugin SDK.
# Please refer to https://docs.langbot.app/en/plugin/dev/tutor.html for more details.
from __future__ import annotations

import json

from typing import Any, AsyncGenerator

from langbot_plugin.api.definition.components.command.command import Command, Subcommand
from langbot_plugin.api.entities.builtin.command.context import ExecuteContext, CommandReturn


class Cmd(Command):
    
    async def initialize(self):
        await super().initialize()
        
        @self.subcommand(
            name="",
            help="Show all registered command",
            usage="cmd",
        )
        async def _(self: Cmd, context: ExecuteContext) -> AsyncGenerator[CommandReturn, None]:

            assume_command_prefix = context.full_command_text[0]

            language = 'en_US'

            output_template = """
Available Commands:

{command_list}
Type `{command_prefix}cmd man <command>` for more detailed manual.
            """.strip()

            commands = await self.plugin.list_commands()

            command_list_str = ''

            for command in commands:
                command_manifest = command['manifest']
                command_list_str += f"{assume_command_prefix}{command_manifest['metadata']['name']} - {command_manifest['metadata']['description'][language]}\n"

            yield CommandReturn(
                text=output_template.format(command_list=command_list_str, command_prefix=assume_command_prefix)
            )
        
        @self.subcommand(
            name="man",
            help="Show the manual of a command",
            usage="cmd man <command>",
        )
        async def man(self: Cmd, context: ExecuteContext) -> AsyncGenerator[CommandReturn, None]:
            print(context)
            
            command_name = context.crt_params[0]
            language = 'en_US'

            commands = await self.plugin.list_commands()

            command_manual = f'Command {command_name} not found'
            for command in commands:
                command_manifest = command['manifest']
                if command_manifest['metadata']['name'] == command_name:
                    command_manual = f'Command {command_name} manual:\n{command_manifest['metadata']['description'][language]}\n'
                    break

            yield CommandReturn(
                text=command_manual
            )
