apiVersion: v1
kind: Command
metadata:
  name: reset
  label:
    en_US: Reset
    zh_Hans: Reset
  description:
    en_US: 'Reset current session and create new conversation'
    zh_Hans: 'Reset current session and create new conversation'
spec:
execution:
  python:
    path: reset.py
    attr: Reset