apiVersion: v1
kind: Plugin
metadata:
  author: RockChinQ
  name: HelloPlugin
  repository: 'https://github.com/langbot-app/langbot-plugin-demo'
  version: 0.1.0
  description:
    en_US: This plugin is an experimental plugin that provides demos on `EventListener`, `Tool` and `Command` components.
    zh_Hans: 这是一个实验性的插件，提供了 `EventListener`、`Tool` 和 `Command` 组件的演示。
  label:
    en_US: HelloPlugin
    zh_Hans: HelloPlugin
  icon: assets/icon.svg
spec:
  config: []
  components:
    EventListener:
      fromDirs:
      - path: components/event_listener/
    Command:
      fromDirs:
      - path: components/commands/
    Tool:
      fromDirs:
      - path: components/tools/
execution:
  python:
    path: main.py
    attr: HelloPlugin
