# Auto generated by LangBot Plugin SDK.
# HumanTakeover - 人工接管与人工回复插件
# Please refer to https://docs.langbot.app/en/plugin/dev/tutor.html for more details.
from __future__ import annotations

import json
import time
import asyncio
import logging
from typing import Any

from langbot_plugin.api.definition.plugin import BasePlugin
from langbot_plugin.api.entities.builtin.platform import message as platform_message

logger = logging.getLogger(__name__)

# 接管静默超时(秒)默认值:接管后若该时长内无人工响应则自动取消接管
DEFAULT_TAKEOVER_TIMEOUT = 600
# 每个会话最多保留的消息条数,避免存储无限膨胀
MAX_MESSAGES_PER_SESSION = 300

# plugin_storage 键名
STORAGE_KEY_SESSIONS = "ht_sessions"
STORAGE_KEY_MESSAGES = "ht_messages"


class HumanTakeover(BasePlugin):
    """人工接管插件主类。

    维护所有会话(私聊/群聊)、消息记录与接管状态,并通过 LangBot 的
    plugin_storage(数据库支撑)持久化,保证重启不丢失数据。
    """

    # 内存缓存
    sessions: dict[str, dict[str, Any]]
    """会话元数据:{session_key: {...}}"""
    messages: dict[str, list[dict[str, Any]]]
    """消息记录:{session_key: [ {role, sender_id, sender_name, content_type, content, ts}, ... ]}"""

    _lock: asyncio.Lock
    _loaded: bool

    async def initialize(self) -> None:
        """插件启动时调用:从持久化存储载入会话与消息缓存。"""
        self.sessions = {}
        self.messages = {}
        self._lock = asyncio.Lock()
        self._loaded = False
        try:
            await self._load_all()
            self._loaded = True
            logger.info(
                "HumanTakeover initialized: %d sessions, %d message buckets loaded",
                len(self.sessions),
                len(self.messages),
            )
        except Exception as e:  # noqa: BLE001
            logger.error("HumanTakeover failed to load persisted data: %s", e)

    def __del__(self) -> None:
        # Will be called when plugin is terminating
        pass

    # ==================== 持久化 ====================

    async def _load_all(self) -> None:
        """从 plugin_storage 载入全部数据到内存。"""
        try:
            keys = await self.get_plugin_storage_keys()
        except Exception as e:  # noqa: BLE001
            logger.warning("HumanTakeover get_plugin_storage_keys failed: %s", e)
            keys = []

        if STORAGE_KEY_SESSIONS in keys:
            try:
                raw = await self.get_plugin_storage(STORAGE_KEY_SESSIONS)
                self.sessions = json.loads(raw.decode("utf-8")) or {}
            except Exception as e:  # noqa: BLE001
                logger.warning("HumanTakeover load sessions failed: %s", e)
                self.sessions = {}

        if STORAGE_KEY_MESSAGES in keys:
            try:
                raw = await self.get_plugin_storage(STORAGE_KEY_MESSAGES)
                self.messages = json.loads(raw.decode("utf-8")) or {}
            except Exception as e:  # noqa: BLE001
                logger.warning("HumanTakeover load messages failed: %s", e)
                self.messages = {}

    async def _persist_sessions(self) -> None:
        try:
            await self.set_plugin_storage(
                STORAGE_KEY_SESSIONS,
                json.dumps(self.sessions, ensure_ascii=False).encode("utf-8"),
            )
        except Exception as e:  # noqa: BLE001
            logger.error("HumanTakeover persist sessions failed: %s", e)

    async def _persist_messages(self) -> None:
        try:
            await self.set_plugin_storage(
                STORAGE_KEY_MESSAGES,
                json.dumps(self.messages, ensure_ascii=False).encode("utf-8"),
            )
        except Exception as e:  # noqa: BLE001
            logger.error("HumanTakeover persist messages failed: %s", e)

    async def clear_all(self) -> None:
        """清理所有存储的会话与消息数据。"""
        async with self._lock:
            self.sessions = {}
            self.messages = {}
        # 先尝试删除;若删除失败(如 key 不存在),回退为写入空数据,确保重启后不恢复
        try:
            await self.delete_plugin_storage(STORAGE_KEY_SESSIONS)
        except Exception as e:  # noqa: BLE001
            logger.warning(
                "HumanTakeover delete sessions storage failed, fallback to empty: %s", e
            )
            await self._persist_sessions()
        try:
            await self.delete_plugin_storage(STORAGE_KEY_MESSAGES)
        except Exception as e:  # noqa: BLE001
            logger.warning(
                "HumanTakeover delete messages storage failed, fallback to empty: %s", e
            )
            await self._persist_messages()
        logger.info("HumanTakeover storage cleared by user")

    # ==================== 会话与消息 ====================

    # ==================== 配置读取 ====================

    def get_takeover_timeout(self) -> int:
        """读取接管超时配置(秒),默认 600。"""
        try:
            cfg = self.get_config() or {}
            val = int(cfg.get("takeover_timeout") or DEFAULT_TAKEOVER_TIMEOUT)
            return val if val > 0 else DEFAULT_TAKEOVER_TIMEOUT
        except Exception:  # noqa: BLE001
            return DEFAULT_TAKEOVER_TIMEOUT

    def get_trigger_words(self) -> list[str]:
        """读取触发词列表。"""
        try:
            cfg = self.get_config() or {}
            words = cfg.get("trigger_words") or []
            return [str(w).strip() for w in words if str(w).strip()]
        except Exception:  # noqa: BLE001
            return []

    def get_auto_takeover_on_trigger(self) -> bool:
        """命中触发词时是否自动接管。"""
        try:
            cfg = self.get_config() or {}
            val = cfg.get("auto_takeover_on_trigger")
            return True if val is None else bool(val)
        except Exception:  # noqa: BLE001
            return True

    def match_trigger(self, text: str) -> str | None:
        """返回命中的第一个触发词,未命中返回 None。"""
        if not text:
            return None
        for w in self.get_trigger_words():
            if w and w in text:
                return w
        return None

    # ==================== 会话与消息 ====================

    @staticmethod
    def make_session_key(launcher_type: str, launcher_id: Any) -> str:
        return f"{launcher_type}_{launcher_id}"

    def _ensure_session(
        self,
        session_key: str,
        session_type: str,
        target_id: str,
        bot_uuid: str,
        name: str,
        adapter: str = "",
    ) -> dict[str, Any]:
        sess = self.sessions.get(session_key)
        if sess is None:
            sess = {
                "session_key": session_key,
                "type": session_type,  # person / group
                "target_id": str(target_id),
                "bot_uuid": bot_uuid,
                "name": name or str(target_id),
                "adapter": "",              # 消息平台适配器(收消息时缓存)
                "members": {},  # group: {member_id: member_name}
                "last_msg_at": 0,
                "last_msg_preview": "",
                "unread": False,            # 未处理标记(触发词命中,类似微信红点)
                "triggered_word": "",       # 命中的触发词
                "takeover": {
                    "active": False,
                    "started_at": 0,
                    "last_human_at": 0,
                },
            }
            self.sessions[session_key] = sess
        else:
            # 更新可能变化的元数据
            if bot_uuid:
                sess["bot_uuid"] = bot_uuid
            if name:
                sess["name"] = name
        if adapter:
            sess["adapter"] = adapter
        return sess

    async def record_message(
        self,
        *,
        session_key: str,
        session_type: str,
        target_id: str,
        bot_uuid: str,
        session_name: str,
        role: str,
        sender_id: str,
        sender_name: str,
        content_type: str,
        content: str,
        adapter: str = "",
    ) -> None:
        """记录一条消息(用户/AI/人工)并更新会话元数据。"""
        async with self._lock:
            sess = self._ensure_session(
                session_key, session_type, target_id, bot_uuid, session_name, adapter
            )
            # 群聊记录发言用户
            if session_type == "group" and sender_id:
                sess.setdefault("members", {})[str(sender_id)] = sender_name or str(
                    sender_id
                )

            now = time.time()
            entry = {
                "role": role,  # user / ai / human
                "sender_id": str(sender_id) if sender_id else "",
                "sender_name": sender_name or "",
                "content_type": content_type,  # text / image
                "content": content,
                "ts": now,
            }
            bucket = self.messages.setdefault(session_key, [])
            bucket.append(entry)
            # 截断,避免无限增长
            if len(bucket) > MAX_MESSAGES_PER_SESSION:
                del bucket[: len(bucket) - MAX_MESSAGES_PER_SESSION]

            sess["last_msg_at"] = now
            preview = content if content_type == "text" else "[图片]"
            sess["last_msg_preview"] = (preview or "")[:50]

        await self._persist_sessions()
        await self._persist_messages()

    # ==================== 接管状态 ====================

    def is_taken_over(self, session_key: str) -> bool:
        """判断会话当前是否处于接管状态(并惰性处理超时)。"""
        sess = self.sessions.get(session_key)
        if not sess:
            return False
        takeover = sess.get("takeover", {})
        if not takeover.get("active"):
            return False
        # 惰性超时判定
        last_human = takeover.get("last_human_at") or takeover.get("started_at") or 0
        if time.time() - last_human >= self.get_takeover_timeout():
            takeover["active"] = False
            logger.info("HumanTakeover session %s auto-released (timeout)", session_key)
            return False
        return True

    def takeover_remaining(self, session_key: str) -> int:
        """返回接管剩余秒数;未接管返回 0。"""
        sess = self.sessions.get(session_key)
        if not sess:
            return 0
        takeover = sess.get("takeover", {})
        if not takeover.get("active"):
            return 0
        last_human = takeover.get("last_human_at") or takeover.get("started_at") or 0
        remaining = int(self.get_takeover_timeout() - (time.time() - last_human))
        return max(0, remaining)

    async def set_takeover(self, session_key: str, active: bool) -> bool:
        """开启或取消接管。"""
        async with self._lock:
            sess = self.sessions.get(session_key)
            if not sess:
                return False
            takeover = sess.setdefault(
                "takeover", {"active": False, "started_at": 0, "last_human_at": 0}
            )
            now = time.time()
            takeover["active"] = active
            if active:
                takeover["started_at"] = now
                takeover["last_human_at"] = now
                logger.info("HumanTakeover session %s taken over", session_key)
            else:
                logger.info("HumanTakeover session %s released", session_key)
        await self._persist_sessions()
        return True

    async def touch_human_response(self, session_key: str) -> None:
        """人工回复时刷新最后响应时间,重置 10 分钟计时。"""
        async with self._lock:
            sess = self.sessions.get(session_key)
            if not sess:
                return
            takeover = sess.setdefault(
                "takeover", {"active": False, "started_at": 0, "last_human_at": 0}
            )
            takeover["last_human_at"] = time.time()
        await self._persist_sessions()

    async def mark_unread(self, session_key: str, word: str) -> None:
        """标记会话为未处理(触发词命中),用于前端红点提醒。"""
        async with self._lock:
            sess = self.sessions.get(session_key)
            if not sess:
                return
            sess["unread"] = True
            sess["triggered_word"] = word or ""
        await self._persist_sessions()
        logger.info(
            "HumanTakeover session %s marked unread by trigger word '%s'",
            session_key,
            word,
        )

    async def clear_unread(self, session_key: str) -> None:
        """清除会话未处理标记(人工打开/处理后调用)。"""
        async with self._lock:
            sess = self.sessions.get(session_key)
            if not sess:
                return
            sess["unread"] = False
            sess["triggered_word"] = ""
        await self._persist_sessions()

    async def expire_timeouts(self) -> None:
        """批量处理所有会话的接管超时(供 Page 轮询时调用)。"""
        changed = False
        now = time.time()
        for sess in self.sessions.values():
            takeover = sess.get("takeover", {})
            if takeover.get("active"):
                last_human = (
                    takeover.get("last_human_at") or takeover.get("started_at") or 0
                )
                if now - last_human >= self.get_takeover_timeout():
                    takeover["active"] = False
                    changed = True
                    logger.info(
                        "HumanTakeover session %s auto-released (timeout sweep)",
                        sess.get("session_key"),
                    )
        if changed:
            await self._persist_sessions()

    # ==================== 人工发送消息 ====================

    async def human_send(
        self,
        session_key: str,
        text: str | None = None,
        image_base64: str | None = None,
        file_base64: str | None = None,
        file_name: str | None = None,
    ) -> tuple[bool, str]:
        """人工通过 Web 面板发送消息(文本 / base64 图片 / base64 文件)到目标会话。

        返回 (是否成功, 错误信息)。
        """
        sess = self.sessions.get(session_key)
        if not sess:
            return False, "session not found"

        bot_uuid = sess.get("bot_uuid") or ""
        target_type = sess.get("type") or "person"
        target_id = sess.get("target_id") or ""

        if not bot_uuid:
            return False, "bot_uuid unknown for this session"

        components: list[platform_message.MessageComponent] = []
        content_repr = ""
        content_type = "text"

        if text:
            components.append(platform_message.Plain(text=text))
            content_repr = text
            content_type = "text"

        if image_base64:
            # 期望前端传入完整 data URL: data:image/png;base64,xxxx
            components.append(platform_message.Image(base64=image_base64))
            content_type = "image"
            content_repr = image_base64

        if file_base64:
            components.append(
                platform_message.File(base64=file_base64, name=file_name or "file")
            )
            content_type = "file"
            content_repr = file_name or "file"

        if not components:
            return False, "empty message"

        # 组装可读的发送内容描述:文本输出内容,图片标注,文件仅输出文件名
        parts = []
        if text:
            parts.append("文本: " + text)
        if image_base64:
            parts.append("[图片]")
        if file_base64:
            parts.append("[文件] " + (file_name or "file"))
        content_log = " | ".join(parts)

        # 目标用户名与适配器(适配器优先用收消息时缓存的值,避免发送时反复请求)
        target_name = sess.get("name") or str(target_id)
        adapter = sess.get("adapter") or "未知"

        logger.info(
            "HumanTakeover 人工发送 -> 用户[%s](%s) 适配器[%s]: %s",
            target_name,
            target_id,
            adapter,
            content_log,
        )

        try:
            await self.send_message(
                bot_uuid=bot_uuid,
                target_type=target_type,
                target_id=str(target_id),
                message_chain=platform_message.MessageChain(components),
            )
        except Exception as e:  # noqa: BLE001
            logger.error(
                "HumanTakeover human_send failed for %s: %s", session_key, e
            )
            return False, str(e)

        # 记录人工消息并刷新接管计时
        # 若包含文本和图片,分别记录两条
        if text:
            await self.record_message(
                session_key=session_key,
                session_type=target_type,
                target_id=str(target_id),
                bot_uuid=bot_uuid,
                session_name=sess.get("name", ""),
                role="human",
                sender_id="",
                sender_name="人工客服",
                content_type="text",
                content=text,
            )
        if image_base64:
            await self.record_message(
                session_key=session_key,
                session_type=target_type,
                target_id=str(target_id),
                bot_uuid=bot_uuid,
                session_name=sess.get("name", ""),
                role="human",
                sender_id="",
                sender_name="人工客服",
                content_type="image",
                content=image_base64,
            )

        if file_base64:
            await self.record_message(
                session_key=session_key,
                session_type=target_type,
                target_id=str(target_id),
                bot_uuid=bot_uuid,
                session_name=sess.get("name", ""),
                role="human",
                sender_id="",
                sender_name="人工客服",
                content_type="file",
                content=file_name or "file",
            )

        await self.touch_human_response(session_key)
        return True, ""
